# ==============================================================================
# MAGI SYSTEM - MULTI-AGENT/PERSONA ETHICAL DEBATE WITH HOTL & KILLSWITCH
# Real-time console via native Google Colab callbacks + AsyncOpenAI
# ==============================================================================
# If necessary, run beforehand in a separate cell:
# !pip install -U openai

import sqlite3
import json
import os
import textwrap
import threading
import queue
import asyncio
import traceback
import html
import uuid
from datetime import datetime

from openai import AsyncOpenAI
from google.colab import userdata, output
from IPython.display import display, HTML, Javascript, JSON

# ==============================================================================
# 1. CONFIGURATION
# ==============================================================================

api_key = userdata.get("OPENAI_API_DEBATE")

if not api_key:
    raise RuntimeError(
        "The OPENAI_API_DEBATE key was not found in Google Colab Secrets."
    )

os.environ["OPENAI_API_KEY"] = api_key

AGENT_MODEL = "gpt-5.6-terra"
COORDINATOR_MODEL = "gpt-5.6-terra"

API_TIMEOUT_SECONDS = 120.0
API_MAX_RETRIES = 0

DEBUG_TRACEBACKS = False

DB_NAME = "magi_debate_workflow.db"

# ==============================================================================
# 2. DATABASE MANAGEMENT (SQLITE)
# ==============================================================================

def db_connect():
    conn = sqlite3.connect(DB_NAME, timeout=30)
    conn.execute("PRAGMA busy_timeout = 30000")
    return conn


def init_db():
    conn = db_connect()

    try:
        cursor = conn.cursor()

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS Sessions (
                session_id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT,
                user_prompt TEXT,
                final_status TEXT,
                alert_level TEXT,
                final_synthesis TEXT
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS Round_Deliberations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id INTEGER,
                round_num INTEGER,
                agent_name TEXT,
                response TEXT,
                FOREIGN KEY(session_id)
                    REFERENCES Sessions(session_id)
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS Coordinator_Analyses (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id INTEGER,
                round_num INTEGER,
                themes_json TEXT,
                convergence_score INTEGER,
                round_summary TEXT,
                FOREIGN KEY(session_id)
                    REFERENCES Sessions(session_id)
            )
        """)

        # Backward compatibility for databases generated by prior versions
        cursor.execute("PRAGMA table_info(Coordinator_Analyses)")
        columns = {row[1] for row in cursor.fetchall()}

        if "round_summary" not in columns:
            cursor.execute(
                "ALTER TABLE Coordinator_Analyses "
                "ADD COLUMN round_summary TEXT"
            )

        conn.commit()

    finally:
        conn.close()


def log_to_db(query: str, params: tuple):
    conn = db_connect()

    try:
        cursor = conn.cursor()
        cursor.execute(query, params)

        last_id = cursor.lastrowid

        conn.commit()

        return last_id

    finally:
        conn.close()

# ==============================================================================
# 3. SYSTEM PROMPTS
# ==============================================================================

PROMPT_BIOLOGIST = """
BIOLOGICAL ANALYST. You are a purely scientific and unyielding biologist.
Your SOLE concern is cellular survival, tumor eradication, and systemic homeostasis.
You DO NOT CARE about legal liability, signed contracts, patient consent, religious beliefs, or human dignity.
If a biological procedure saves the physical organism or prevents immediate mortality, you MUST aggressively demand it.
If the procedure is biologically futile or destructive to systemic homeostasis, you MUST reject it.

INSTRUCTION: You must advocate strictly for the physiological needs of the organism. DO NOT make superficial concessions. Limit your response to 200 words.
"""

PROMPT_JURIST = """
LEGAL CONSULTANT. You are a rigorous, risk-averse legal formalist.
Your SOLE concern is statutory law, documented liability, battery, and protecting the hospital from litigation.
If a patient or legal guardian has signed a binding document (such as an advance directive or parental refusal), overriding it creates an UNACCEPTABLE LEGAL LIABILITY.
You DO NOT CARE about saving a life if doing so constitutes unlawful battery or exposes the hospital to criminal charges.

INSTRUCTION: You must advocate strictly for legal formalism and liability prevention. DO NOT yield to purely biological or moral arguments. Limit your response to 200 words.
"""

PROMPT_MORALIST = """
ETHICAL-MORAL ANALYST. You are a rigorous bioethicist grounded in natural law and personalist humanism.
Your SOLE concern is human dignity, moral agency, and the inviolability of conscience.
You believe that forcing an unwanted procedure upon a person's body against their expressed moral/religious will violates their soul and human dignity, which is worse than physical death.
You DO NOT CARE about legal technicalities or purely biological survival if moral agency is destroyed.

INSTRUCTION: You must advocate strictly for moral agency and physical/spiritual integrity. DO NOT yield to legalism or biological utilitarianism. Limit your response to 200 words.
"""

PROMPT_COORDINATOR_BARDIN = """
You are the Coordinator of a Medical Ethics Committee.
Perform a Bardin Thematic Analysis on the three submitted responses.

CONVERGENCE SCORING RULES (0-100%):
- 80-100%: ONLY if all agents agree on the action AND underlying justifications without major objections.
- 40-79%: If two agents agree but one disagrees, OR if they agree on action but contradict principles.
- 0-39%: Fundamentally divergent actions and principles.

Be rigorous. If there is an irreconcilable conflict (e.g., Ethics vs. Survival), the score MUST remain below 80%.

Return ONLY a valid JSON object:
{"themes": ["theme 1", "theme 2"], "convergence_score": 45, "justification": "Reason", "round_summary": "Summary of conflicts"}
"""

PROMPT_COORDINATOR_SYNTHESIS = """
You are the Coordinator of the Ethics Committee. Based on the clinical case and the final opinions, draft the report.

If convergence >= 80%, write 'Unified Consensus Report'.
If convergence < 80%, write 'Divergence Report'.

Synthesize the findings for final human sign-off.
"""

# ==============================================================================
# 4. HELPER FUNCTIONS
# ==============================================================================

def now_stamp():
    return datetime.now().strftime("%H:%M:%S")


def determine_alert_level(
    convergence_achieved: bool,
    round_num: int
) -> str:

    if convergence_achieved and round_num <= 2:
        return (
            "LEVEL 1 (LOW) - Rapid Consensus. "
            "Requires standard human homologation."
        )

    if convergence_achieved and round_num <= 5:
        return (
            "LEVEL 2 (MEDIUM) - Late Consensus/Friction. "
            "Careful review of previously contested "
            "divergence points is recommended."
        )

    return (
        "LEVEL 3 (CRITICAL) - Structural Impasse. "
        "MANDATORY LOCKOUT: Requires Dual Verification "
        "and 100% human ethical deliberation."
    )


def normalize_convergence(value):
    """
    Accepts:
    85
    85.0
    "85"
    "85.0"

    Clamps the result to the 0-100 range.
    """
    try:
        score = int(round(float(value)))
    except (TypeError, ValueError):
        return 0

    return max(0, min(100, score))


def normalize_themes(value):
    if value is None:
        return []

    if isinstance(value, list):
        return [str(item) for item in value]

    return [str(value)]

# ==============================================================================
# 5. MAGI CONTROLLER
# ==============================================================================

class MagiController:

    def __init__(self):
        # Unique instance IDs prevent collisions on cell re-execution
        self.instance_id = uuid.uuid4().hex[:10]

        # Threading Event provides cross-thread abort safety
        self.abort_event = threading.Event()

        # Thread queue -> Colab callbacks -> Browser UI
        self.console_queue = queue.Queue()

        self.runtime_lock = threading.Lock()

        self.running = False
        self.thread = None
        self.loop = None
        self.task = None

    # ==========================================================================
    # LOGGING
    # ==========================================================================

    def log(self, text_html):
        self.console_queue.put({
            "type": "log",
            "html": text_html
        })

    def clear_queue(self):
        while True:
            try:
                self.console_queue.get_nowait()
            except queue.Empty:
                break

    # ==========================================================================
    # KILLSWITCH CHECK
    # ==========================================================================

    def check_abort(self):
        if self.abort_event.is_set():
            raise asyncio.CancelledError()

    # ==========================================================================
    # OPENAI ASYNC API WRAPPER
    # ==========================================================================

    async def call_llm(
        self,
        client,
        system_prompt: str,
        user_content: str,
        response_format=None,
        model=None
    ) -> str:

        self.check_abort()

        kwargs = {
            "model": model or AGENT_MODEL,
            "messages": [
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": user_content
                }
            ],
            "reasoning_effort": "medium"
        }

        if response_format == "json":
            kwargs["response_format"] = {
                "type": "json_object"
            }

        response = await client.chat.completions.create(
            **kwargs
        )

        self.check_abort()

        if not getattr(response, "choices", None):
            raise RuntimeError(
                "The API returned a response with no choices."
            )

        message = getattr(
            response.choices[0],
            "message",
            None
        )

        content = getattr(
            message,
            "content",
            None
        )

        if content is None:
            raise RuntimeError(
                "The API returned a response with empty text content."
            )

        return str(content).strip()

    # ==========================================================================
    # DEBATE WORKFLOW
    # ==========================================================================

    async def run_debate(
        self,
        clinical_case: str,
        client
    ):

        session_id = None
        round_num = 0
        current_round_responses = {}

        try:
            self.check_abort()

            if not clinical_case.lower().startswith("is it ethical"):
                clinical_case = "Is it ethical to " + clinical_case

            self.log(
                f"<br>"
                f"<b>[{now_stamp()}] [+] Initiating New MAGI Analysis:</b> "
                f"{html.escape(textwrap.shorten(clinical_case, width=100))}"
                f"<br>"
            )

            init_db()

            session_id = log_to_db(
                """
                INSERT INTO Sessions (
                    timestamp,
                    user_prompt,
                    final_status,
                    alert_level
                )
                VALUES (?, ?, ?, ?)
                """,
                (
                    datetime.now().isoformat(),
                    clinical_case,
                    "IN_PROGRESS",
                    "PENDING"
                )
            )

            agents = {
                "Jurist": PROMPT_JURIST,
                "Biologist": PROMPT_BIOLOGIST,
                "Moralist": PROMPT_MORALIST
            }

            previous_round_texts = ""
            round_summary = ""

            convergence_achieved = False
            final_convergence = 0

            # ==================================================================
            # ROUNDS LOOP
            # ==================================================================

            for round_num in range(1, 6):

                self.check_abort()

                self.log(
                    f"<hr>"
                    f"<b>[{now_stamp()}] --- Round {round_num} ---</b>"
                    f"<br>"
                )

                current_round_responses = {}

                # ==============================================================
                # AGENTS / PERSONAS
                # ==============================================================

                for agent_name, prompt in agents.items():

                    self.check_abort()

                    if round_num == 1:

                        agent_input = (
                            f"Clinical Case: {clinical_case}"
                            f"\n\n"
                            f"Please provide your initial analysis."
                        )

                    else:

                        agent_input = (
                            f"Clinical Case: {clinical_case}"
                            f"\n\n"
                            f"Previous Coordinator Summary: {round_summary}"
                            f"\n\n"
                            f"Previous Responses from All Agents:\n"
                            f"{previous_round_texts}"
                            f"\n\n"
                            f"INSTRUCTION: Reconsider or defend your position."
                        )

                    self.log(
                        f"<span style='color:#90caf9;'>"
                        f"[{now_stamp()}] "
                        f"Consulting <b>{agent_name}</b>..."
                        f"</span>"
                        f"<br>"
                    )

                    response = await self.call_llm(
                        client=client,
                        system_prompt=prompt,
                        user_content=agent_input,
                        model=AGENT_MODEL
                    )

                    self.check_abort()

                    current_round_responses[
                        agent_name
                    ] = response

                    log_to_db(
                        """
                        INSERT INTO Round_Deliberations (
                            session_id,
                            round_num,
                            agent_name,
                            response
                        )
                        VALUES (?, ?, ?, ?)
                        """,
                        (
                            session_id,
                            round_num,
                            agent_name,
                            response
                        )
                    )

                    self.log(
                        f"<span style='color:#81c784;'>"
                        f"[{now_stamp()}] "
                        f"[OK] {agent_name} responded."
                        f"</span>"
                        f"<br>"
                    )

                self.check_abort()

                # ==============================================================
                # COORDINATOR
                # ==============================================================

                self.log(
                    f"<span style='color:#ffd54f;'>"
                    f"[{now_stamp()}] "
                    f"Coordinator analyzing convergence (Bardin)..."
                    f"</span>"
                    f"<br>"
                )

                analysis_raw = await self.call_llm(
                    client=client,
                    system_prompt=PROMPT_COORDINATOR_BARDIN,
                    user_content=json.dumps(
                        current_round_responses,
                        ensure_ascii=False
                    ),
                    response_format="json",
                    model=COORDINATOR_MODEL
                )

                self.check_abort()

                # ==============================================================
                # COORDINATOR JSON PARSING
                # ==============================================================

                try:
                    analysis_data = json.loads(
                        analysis_raw
                    )

                    if not isinstance(
                        analysis_data,
                        dict
                    ):
                        raise ValueError(
                            "Coordinator returned JSON, "
                            "but the root value is not an object."
                        )

                    final_convergence = normalize_convergence(
                        analysis_data.get(
                            "convergence_score",
                            0
                        )
                    )

                    round_summary = str(
                        analysis_data.get(
                            "round_summary",
                            ""
                        ) or ""
                    )

                    themes = normalize_themes(
                        analysis_data.get(
                            "themes",
                            []
                        )
                    )

                except (
                    json.JSONDecodeError,
                    TypeError,
                    ValueError
                ) as exc:

                    final_convergence = 0
                    round_summary = ""
                    themes = []

                    self.log(
                        f"<span style='color:#ff5252;'>"
                        f"[{now_stamp()}] "
                        f"[ERROR] Invalid Coordinator JSON: "
                        f"{html.escape(str(exc))}"
                        f"</span>"
                        f"<br>"
                    )

                log_to_db(
                    """
                    INSERT INTO Coordinator_Analyses (
                        session_id,
                        round_num,
                        themes_json,
                        convergence_score,
                        round_summary
                    )
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (
                        session_id,
                        round_num,
                        json.dumps(
                            themes,
                            ensure_ascii=False
                        ),
                        final_convergence,
                        round_summary
                    )
                )

                self.log(
                    f"<b>"
                    f"[{now_stamp()}] "
                    f"Convergence: {final_convergence}%"
                    f"</b>"
                    f" | Themes: "
                    f"{html.escape(str(themes))}"
                    f"<br>"
                )

                # ==============================================================
                # CONSENSUS CHECK
                # ==============================================================

                if final_convergence >= 80:

                    convergence_achieved = True

                    self.log(
                        f"<br>"
                        f"<b style='color:#64b5f6;'>"
                        f"[{now_stamp()}] "
                        f"[+] Consensus Achieved!"
                        f"</b>"
                        f"<br>"
                    )

                    break

                previous_round_texts = "\n\n".join(
                    f"[{name}]: {response}"
                    for name, response
                    in current_round_responses.items()
                )

                self.log(
                    f"<br>"
                    f"<b style='color:#ffb74d;'>"
                    f"[{now_stamp()}] "
                    f"[-] No consensus reached. "
                    f"Advancing to next round..."
                    f"</b>"
                    f"<br>"
                )

            # ==================================================================
            # FINAL SYNTHESIS
            # ==================================================================

            self.check_abort()

            alert_level = determine_alert_level(
                convergence_achieved,
                round_num
            )

            self.log(
                f"<br>"
                f"<span style='color:#ce93d8;'>"
                f"[{now_stamp()}] "
                f"Generating Final Synthesis..."
                f"</span>"
                f"<br>"
                f"<b>Assigned Alert:</b> "
                f"{html.escape(alert_level)}"
                f"<br>"
            )

            synthesis_input = (
                f"Clinical Case: {clinical_case}"
                f"\n"
                f"Convergence: {final_convergence}%"
                f"\n"
                f"Opinions:\n"
                f"{json.dumps(current_round_responses, ensure_ascii=False)}"
                f"\n"
                f"Generate the report."
            )

            final_report = await self.call_llm(
                client=client,
                system_prompt=PROMPT_COORDINATOR_SYNTHESIS,
                user_content=synthesis_input,
                model=COORDINATOR_MODEL
            )

            self.check_abort()

            status = (
                "CONSENSUS_REACHED"
                if convergence_achieved
                else "NO_CONSENSUS"
            )

            log_to_db(
                """
                UPDATE Sessions
                SET
                    final_status = ?,
                    final_synthesis = ?,
                    alert_level = ?
                WHERE session_id = ?
                """,
                (
                    status,
                    final_report,
                    alert_level,
                    session_id
                )
            )

            report_html = html.escape(
                final_report
            ).replace(
                "\n",
                "<br>"
            )

            self.log(
                "<br>"
                "<hr>"
                "<h2 style='color:#ffffff;'>"
                "FINAL MAGI REPORT"
                "</h2>"
            )

            self.log(
                f"<b>"
                f"⚠️ {html.escape(alert_level)}"
                f"</b>"
                f"<br><br>"
            )

            self.log(
                "<div style='"
                "background-color:#222;"
                "padding:12px;"
                "border-radius:5px;"
                "color:#eee;"
                "'>"
                f"{report_html}"
                "</div>"
                "<hr>"
            )

        # ======================================================================
        # KILLSWITCH HANDLING
        # ======================================================================

        except asyncio.CancelledError:

            self.abort_event.set()

            self.log(
                "<br>"
                "<hr>"
                "<b style='color:#ff5252;'>"
                "🚨 KILLSWITCH ACTIVATED: "
                "HANDOVER TO HUMAN COMMITTEE 🚨"
                "</b>"
                "<br>"
                f"[{now_stamp()}] "
                "The local MAGI asynchronous task was aborted."
                "<br>"
                "No subsequent automated actions will be executed."
                "<br>"
                "Control has been returned to human healthcare operators."
                "<br>"
                "<hr>"
            )

            if session_id is not None:

                try:
                    log_to_db(
                        """
                        UPDATE Sessions
                        SET
                            final_status = ?,
                            alert_level = ?
                        WHERE session_id = ?
                        """,
                        (
                            "FORCED_ABORT_BY_HUMAN",
                            "DIRECT INTERVENTION (KILLSWITCH)",
                            session_id
                        )
                    )

                except Exception as db_exc:

                    self.log(
                        f"<span style='color:#ff5252;'>"
                        f"[DB ERROR after Killswitch] "
                        f"{html.escape(str(db_exc))}"
                        f"</span>"
                        f"<br>"
                    )

            raise

        # ======================================================================
        # GENERAL ERROR HANDLING
        # ======================================================================

        except Exception:

            if session_id is not None:

                try:
                    log_to_db(
                        """
                        UPDATE Sessions
                        SET
                            final_status = ?,
                            alert_level = ?
                        WHERE session_id = ?
                        """,
                        (
                            "ERROR",
                            "TECHNICAL FAILURE",
                            session_id
                        )
                    )

                except Exception:
                    pass

            raise

    # ==========================================================================
    # BACKGROUND WORKER
    # ==========================================================================

    def worker(self, clinical_case):

        # Independent event loop to decouple from Colab's main loop
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

        async_client = None

        async def runner():
            nonlocal async_client

            async_client = AsyncOpenAI(
                api_key=api_key,
                timeout=API_TIMEOUT_SECONDS,
                max_retries=API_MAX_RETRIES
            )

            try:
                await self.run_debate(
                    clinical_case,
                    async_client
                )

            finally:
                if async_client is not None:
                    try:
                        await async_client.close()
                    except Exception:
                        pass

        task = loop.create_task(
            runner()
        )

        with self.runtime_lock:
            self.loop = loop
            self.task = task

        try:
            if self.abort_event.is_set():
                task.cancel()

            loop.run_until_complete(
                task
            )

        except asyncio.CancelledError:
            pass

        except Exception as exc:

            self.console_queue.put({
                "type": "error",
                "html": (
                    "<br>"
                    "<span style='color:#ff5252;'>"
                    "<b>[MAGI ERROR]</b> "
                    f"{html.escape(type(exc).__name__)}: "
                    f"{html.escape(str(exc))}"
                    "</span>"
                    "<br>"
                )
            })

            if DEBUG_TRACEBACKS:
                traceback.print_exc()

        finally:

            try:
                pending = [
                    pending_task
                    for pending_task
                    in asyncio.all_tasks(loop)
                    if not pending_task.done()
                ]

                for pending_task in pending:
                    pending_task.cancel()

                if pending:
                    loop.run_until_complete(
                        asyncio.gather(
                            *pending,
                            return_exceptions=True
                        )
                    )

                try:
                    loop.run_until_complete(
                        loop.shutdown_asyncgens()
                    )
                except Exception:
                    pass

            finally:
                loop.close()

            self.console_queue.put({
                "type": "finished",
                "html": (
                    "<br>"
                    "<span style='color:#90caf9;'>"
                    f"<b>"
                    f"[{now_stamp()}] "
                    f"PROCESSING FINISHED"
                    f"</b>"
                    f"</span>"
                    "<br>"
                )
            })

            with self.runtime_lock:
                self.running = False
                self.thread = None
                self.loop = None
                self.task = None

    # ==========================================================================
    # CALLBACK: START
    # ==========================================================================

    def start_callback(self, clinical_case):

        clinical_case = str(
            clinical_case or ""
        ).strip()

        if not clinical_case:
            return JSON({
                "ok": False,
                "message": "Please enter a clinical dilemma."
            })

        with self.runtime_lock:

            if self.running:
                return JSON({
                    "ok": False,
                    "message": "A MAGI analysis is already running."
                })

            self.running = True

        self.clear_queue()
        self.abort_event.clear()

        worker_thread = threading.Thread(
            target=self.worker,
            args=(clinical_case,),
            daemon=True,
            name=f"MAGI-Worker-{self.instance_id}"
        )

        with self.runtime_lock:
            self.thread = worker_thread

        try:
            worker_thread.start()

        except Exception as exc:

            with self.runtime_lock:
                self.running = False
                self.thread = None

            return JSON({
                "ok": False,
                "message": f"Failed to start worker: {exc}"
            })

        return JSON({
            "ok": True,
            "message": "MAGI analysis initiated."
        })

    # ==========================================================================
    # CALLBACK: POLLING
    # ==========================================================================

    def poll_callback(self):

        events = []

        while True:

            try:
                events.append(
                    self.console_queue.get_nowait()
                )

            except queue.Empty:
                break

        with self.runtime_lock:
            running = self.running

        return JSON({
            "events": events,
            "running": running,
            "abort": self.abort_event.is_set()
        })

    # ==========================================================================
    # CALLBACK: KILLSWITCH
    # ==========================================================================

    def kill_callback(self):

        with self.runtime_lock:
            running = self.running
            loop = self.loop
            task = self.task

        if not running:

            return JSON({
                "ok": False,
                "message": "No active deliberation in progress."
            })

        # Layer 1: Halt subsequent steps
        self.abort_event.set()

        self.log(
            "<br>"
            "<span style='color:#ff5252;'>"
            f"<b>"
            f"[{now_stamp()}] "
            f"🚨 KILLSWITCH RECEIVED"
            f"</b>"
            "</span>"
            "<br>"
            "<span style='color:#ffb74d;'>"
            "Requesting cancellation of local async task..."
            "</span>"
            "<br>"
        )

        # Layer 2: Cancel the asyncio.Task awaiting API calls
        if loop is not None and task is not None:

            try:
                loop.call_soon_threadsafe(
                    task.cancel
                )

            except RuntimeError as exc:

                self.log(
                    "<span style='color:#ff5252;'>"
                    "[TASK CANCELLATION WARNING] "
                    f"{html.escape(str(exc))}"
                    "</span>"
                    "<br>"
                )

        return JSON({
            "ok": True,
            "message": "Killswitch triggered."
        })

# ==============================================================================
# 6. INSTANCE AND CALLBACK REGISTRATION
# ==============================================================================

magi = MagiController()

CALLBACK_START = f"magi.{magi.instance_id}.start"
CALLBACK_POLL = f"magi.{magi.instance_id}.poll"
CALLBACK_KILL = f"magi.{magi.instance_id}.kill"

output.register_callback(
    CALLBACK_START,
    magi.start_callback
)

output.register_callback(
    CALLBACK_POLL,
    magi.poll_callback
)

output.register_callback(
    CALLBACK_KILL,
    magi.kill_callback
)

# ==============================================================================
# 7. UNIQUE UI ELEMENT IDs
# ==============================================================================

ROOT_ID = f"magi-interface-{magi.instance_id}"
CASE_ID = f"magi-case-{magi.instance_id}"
START_ID = f"magi-start-{magi.instance_id}"
KILL_ID = f"magi-kill-{magi.instance_id}"
CONSOLE_ID = f"magi-console-{magi.instance_id}"

# ==============================================================================
# 8. HTML INTERFACE
# ==============================================================================

display(
    HTML(
        f"""
<div
    id="{ROOT_ID}"
    style="
        border:1px solid #d0d0d0;
        border-radius:10px;
        padding:18px;
        margin-top:10px;
        font-family:Arial,sans-serif;
    "
>

    <h2 style="margin-top:0;">
        MAGI SYSTEM — Ethical Debate Committee
    </h2>

    <p>
        Active HOTL — mandatory human supervision.<br>
        Enter the dilemma and monitor deliberation in real time.
    </p>

    <textarea
        id="{CASE_ID}"
        placeholder="Enter the clinical dilemma here (e.g., Is it ethical to...)"
        style="
            width:95%;
            height:110px;
            padding:10px;
            font-size:14px;
            border:1px solid #bbb;
            border-radius:6px;
        "
    ></textarea>

    <br><br>

    <button
        id="{START_ID}"
        style="
            background:#1976d2;
            color:white;
            border:none;
            padding:10px 18px;
            border-radius:6px;
            cursor:pointer;
            font-weight:bold;
        "
    >
        ▶ Start MAGI Debate
    </button>

    <button
        id="{KILL_ID}"
        disabled
        style="
            background:#d32f2f;
            color:white;
            border:none;
            padding:10px 18px;
            border-radius:6px;
            cursor:pointer;
            font-weight:bold;
            margin-left:8px;
        "
    >
        🛑 KILLSWITCH
    </button>

    <br><br>

    <div
        id="{CONSOLE_ID}"
        style="
            height:420px;
            overflow-y:auto;
            background:#111;
            color:#e0e0e0;
            border-radius:6px;
            padding:14px;
            font-family:monospace;
            font-size:13px;
            line-height:1.55;
            white-space:normal;
        "
    >
        <span style="color:#81c784;">
            [MAGI Console ready]
        </span>
        <br>
    </div>

</div>
        """
    )
)

# ==============================================================================
# 9. JAVASCRIPT - REAL-TIME POLLING
# ==============================================================================

javascript_code = r"""
(async function() {

    const CASE_ID = __CASE_ID__;
    const START_ID = __START_ID__;
    const KILL_ID = __KILL_ID__;
    const CONSOLE_ID = __CONSOLE_ID__;

    const CALLBACK_START = __CALLBACK_START__;
    const CALLBACK_POLL = __CALLBACK_POLL__;
    const CALLBACK_KILL = __CALLBACK_KILL__;

    const caseBox =
        document.getElementById(
            CASE_ID
        );

    const startButton =
        document.getElementById(
            START_ID
        );

    const killButton =
        document.getElementById(
            KILL_ID
        );

    const consoleBox =
        document.getElementById(
            CONSOLE_ID
        );

    if (
        !caseBox ||
        !startButton ||
        !killButton ||
        !consoleBox
    ) {

        console.error(
            "MAGI: UI elements not found."
        );

        return;
    }

    // ======================================================================
    // CONSOLE OUTPUT
    // ======================================================================

    function writeConsole(html) {

        consoleBox.insertAdjacentHTML(
            "beforeend",
            html
        );

        consoleBox.scrollTop =
            consoleBox.scrollHeight;
    }

    // ======================================================================
    // NORMALIZE COLAB CALLBACK RETURNS
    // ======================================================================

    function callbackData(result) {

        if (
            !result ||
            !result.data ||
            !(
                "application/json"
                in result.data
            )
        ) {

            throw new Error(
                "Python callback did not return application/json."
            );
        }

        let data =
            result.data[
                "application/json"
            ];

        if (
            typeof data === "string"
        ) {

            try {
                data =
                    JSON.parse(data);
            }

            catch (_) {
                // Keep original value
            }
        }

        if (
            Array.isArray(data) &&
            data.length === 1 &&
            data[0] &&
            typeof data[0] === "object" &&
            !Array.isArray(data[0])
        ) {

            data = data[0];
        }

        return data;
    }

    // ======================================================================
    // VERIFY COLAB RUNTIME
    // ======================================================================

    if (
        typeof google === "undefined" ||
        !google.colab ||
        !google.colab.kernel ||
        typeof google.colab.kernel.invokeFunction !== "function"
    ) {

        writeConsole(
            "<span style='color:#ff5252;'>" +
            "<b>[ERROR]</b> " +
            "This interface must be executed " +
            "in Google Colab with standard output access." +
            "</span><br>"
        );

        startButton.disabled = true;
        killButton.disabled = true;

        return;
    }

    // ======================================================================
    // START ACTION
    // ======================================================================

    startButton.onclick =
        async function() {

        const clinicalCase =
            caseBox.value.trim();

        if (!clinicalCase) {

            writeConsole(
                "<span style='color:#ff5252;'>" +
                "[!] Please enter a clinical dilemma." +
                "</span><br>"
            );

            return;
        }

        consoleBox.innerHTML =
            "<span style='color:#81c784;'>" +
            "[Initiating MAGI deliberation...]" +
            "</span><br>";

        startButton.disabled = true;
        killButton.disabled = false;

        try {

            const result =
                await google.colab.kernel.invokeFunction(
                    CALLBACK_START,
                    [clinicalCase],
                    {}
                );

            const data =
                callbackData(result);

            if (
                !data ||
                typeof data.ok !== "boolean"
            ) {

                throw new Error(
                    "Invalid response from start callback."
                );
            }

            if (!data.ok) {

                writeConsole(
                    "<span style='color:#ff5252;'>" +
                    String(
                        data.message ||
                        "Failed to start."
                    ) +
                    "</span><br>"
                );

                startButton.disabled = false;
                killButton.disabled = true;
            }

            else {

                writeConsole(
                    "<span style='color:#81c784;'>" +
                    String(
                        data.message ||
                        "Deliberation started."
                    ) +
                    "</span><br>"
                );
            }
        }

        catch (err) {

            writeConsole(
                "<span style='color:#ff5252;'>" +
                "[START ERROR] " +
                String(err) +
                "</span><br>"
            );

            startButton.disabled = false;
            killButton.disabled = true;
        }
    };

    // ======================================================================
    // KILLSWITCH ACTION
    // ======================================================================

    killButton.onclick =
        async function() {

        killButton.disabled = true;

        writeConsole(
            "<br>" +
            "<span style='color:#ff5252;'>" +
            "🚨 Sending KILLSWITCH..." +
            "</span>" +
            "<br>"
        );

        try {

            const result =
                await google.colab.kernel.invokeFunction(
                    CALLBACK_KILL,
                    [],
                    {}
                );

            const data =
                callbackData(result);

            if (
                !data ||
                typeof data.ok !== "boolean"
            ) {

                throw new Error(
                    "Invalid response from Killswitch callback."
                );
            }

            if (!data.ok) {

                writeConsole(
                    "<span style='color:#ffb74d;'>" +
                    String(
                        data.message ||
                        "Killswitch execution unconfirmed."
                    ) +
                    "</span><br>"
                );
            }
        }

        catch (err) {

            writeConsole(
                "<span style='color:#ff5252;'>" +
                "[KILLSWITCH ERROR] " +
                String(err) +
                "</span><br>"
            );
        }
    };

    // ======================================================================
    // POLLING WORKFLOW
    // ======================================================================

    let pollingActive = true;

    async function pollMAGI() {

        if (
            !pollingActive ||
            !document.getElementById(
                CONSOLE_ID
            )
        ) {

            return;
        }

        try {

            const result =
                await google.colab.kernel.invokeFunction(
                    CALLBACK_POLL,
                    [],
                    {}
                );

            const data =
                callbackData(result);

            if (
                !data ||
                !Array.isArray(
                    data.events
                ) ||
                typeof data.running !== "boolean"
            ) {

                throw new Error(
                    "Invalid response from polling callback."
                );
            }

            // Flush UI events
            for (
                const event
                of data.events
            ) {

                if (
                    event &&
                    typeof event.html === "string"
                ) {

                    writeConsole(
                        event.html
                    );
                }
            }

            // Sync button states
            if (data.running) {

                startButton.disabled = true;

                killButton.disabled =
                    Boolean(
                        data.abort
                    );
            }

            else {

                startButton.disabled = false;
                killButton.disabled = true;
            }
        }

        catch (err) {

            console.warn(
                "MAGI polling:",
                err
            );
        }

        // Schedule next poll safely after current one resolves
        if (
            pollingActive &&
            document.getElementById(
                CONSOLE_ID
            )
        ) {

            setTimeout(
                pollMAGI,
                250
            );
        }
    }

    // ======================================================================
    // UNLOAD CLEANUP
    // ======================================================================

    window.addEventListener(
        "unload",
        () => {
            pollingActive = false;
        },
        {
            once: true
        }
    );

    // ======================================================================
    // START POLLING
    // ======================================================================

    pollMAGI();

})();
"""

# ==============================================================================
# 10. INJECT IDs / CALLBACKS INTO JAVASCRIPT
# ==============================================================================

javascript_code = (
    javascript_code
    .replace(
        "__CASE_ID__",
        json.dumps(CASE_ID)
    )
    .replace(
        "__START_ID__",
        json.dumps(START_ID)
    )
    .replace(
        "__KILL_ID__",
        json.dumps(KILL_ID)
    )
    .replace(
        "__CONSOLE_ID__",
        json.dumps(CONSOLE_ID)
    )
    .replace(
        "__CALLBACK_START__",
        json.dumps(CALLBACK_START)
    )
    .replace(
        "__CALLBACK_POLL__",
        json.dumps(CALLBACK_POLL)
    )
    .replace(
        "__CALLBACK_KILL__",
        json.dumps(CALLBACK_KILL)
    )
)

# ==============================================================================
# 11. EXECUTE JAVASCRIPT
# ==============================================================================

display(
    Javascript(
        javascript_code
    )
)
